//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PkmAutoName.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PkmAutoName.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Derp {
            get {
                object obj = ResourceManager.GetObject("Derp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Hello! Lani here. This is for the DELETED Pokecord bot, not for any other Pokemon bots (including clones and successors). It is left public for anyone that wants to use it as REFERENCE to make their own bots. STOP ASKING ME QUESTIONS.&quot;,,,,,,
        ///CTRL + F to search,&quot;GREEN/YELLOW/ORANGE mean &quot;&quot;probably not possible&quot;&quot;&quot;,,BLUE OUTLINE = CAN MEGA/PRIMAL (p!shop 5),THERE ARE SEVEN COLUMNS. CHECK THEM ALL BEFORE COMMENTING. NO YOU CANNOT HAVE ACCESS TO EDIT.,,
        ///First Stage/Baby,Evolves through -&gt;,Second Stage,Evolves [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Evolutions {
            get {
                return ResourceManager.GetString("Evolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon pikachu_pokeball_pokemon_icon_1320184857556086253 {
            get {
                object obj = ResourceManager.GetObject("pikachu_pokeball_pokemon_icon_1320184857556086253", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Bulbasaur
        ///2,Ivysaur
        ///3,Venusaur
        ///4,Charmander
        ///5,Charmeleon
        ///6,Charizard
        ///7,Squirtle
        ///8,Wartortle
        ///9,Blastoise
        ///10,Caterpie
        ///11,Metapod
        ///12,Butterfree
        ///13,Weedle
        ///14,Kakuna
        ///15,Beedrill
        ///16,Pidgey
        ///17,Pidgeotto
        ///18,Pidgeot
        ///19,Rattata
        ///20,Raticate
        ///21,Spearow
        ///22,Fearow
        ///23,Ekans
        ///24,Arbok
        ///25,Pikachu
        ///26,Raichu
        ///27,Sandshrew
        ///28,Sandslash
        ///29,Nidoran♀
        ///30,Nidorina
        ///31,Nidoqueen
        ///32,Nidoran♂
        ///33,Nidorino
        ///34,Nidoking
        ///35,Clefairy
        ///36,Clefable
        ///37,Vulpix
        ///38,Ninetales
        ///39,Jigglypuff
        ///40,Wigglytuff
        ///41,Zub [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PKM {
            get {
                return ResourceManager.GetString("PKM", resourceCulture);
            }
        }
    }
}
